In [1]:
import numpy as np

In [2]:
x=np.random.rand(2,3)

In [21]:
x

array([[0.43903242, 0.23365028, 0.57927158],
       [0.13797381, 0.98832726, 0.06855412]])

In [20]:
x[:,:,np.newaxis]

array([[[0.43903242],
        [0.23365028],
        [0.57927158]],

       [[0.13797381],
        [0.98832726],
        [0.06855412]]])

In [6]:
y=np.random.rand(3)

In [9]:
y.reshape(1,3)

array([[0.11490803, 0.38510317, 0.86770439]])

In [13]:
y.reshape(1,3).T

array([[0.11490803],
       [0.38510317],
       [0.86770439]])

In [5]:
x.T

array([[0.43903242, 0.13797381],
       [0.23365028, 0.98832726],
       [0.57927158, 0.06855412]])

In [49]:
x+a

array([[1.34344145, 2.44523845, 3.56638642, 4.18955756, 5.10006285],
       [1.48967477, 2.27905591, 3.52758118, 4.8560713 , 5.62697442],
       [1.22503087, 2.43676937, 3.92652263, 4.5076331 , 5.14309145]])

In [50]:
row=[0,1,2]
col=[0,1,2]
x[row,col]

array([0.34344145, 0.27905591, 0.92652263])

In [43]:
y=[1,2,3,4,5]

In [44]:
y[0]=0

In [45]:
y

[0, 2, 3, 4, 5]