In [1]:
import numpy as np

In [46]:
x=np.random.rand(3,5)

In [47]:
x

array([[0.34344145, 0.44523845, 0.56638642, 0.18955756, 0.10006285],
       [0.48967477, 0.27905591, 0.52758118, 0.8560713 , 0.62697442],
       [0.22503087, 0.43676937, 0.92652263, 0.5076331 , 0.14309145]])

In [48]:
a=np.array([1,2,3,4,5])

In [49]:
x+a

array([[1.34344145, 2.44523845, 3.56638642, 4.18955756, 5.10006285],
       [1.48967477, 2.27905591, 3.52758118, 4.8560713 , 5.62697442],
       [1.22503087, 2.43676937, 3.92652263, 4.5076331 , 5.14309145]])

In [50]:
row=[0,1,2]
col=[0,1,2]
x[row,col]

array([0.34344145, 0.27905591, 0.92652263])

In [43]:
y=[1,2,3,4,5]

In [44]:
y[0]=0

In [45]:
y

[0, 2, 3, 4, 5]